services:
  app:
    build:
      context: .
      target: development
    command: rm -rf dist && tsc -watch & nodemon --legacy-watch --inspect=0.0.0.0:9229 dist/main.js
    env_file: .env
    restart: always
    ports:
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
